import Foundation
import PackagePlugin

// Generates `kHaishinKitRevision` from the checkout's git HEAD at build time, so
// runtime logs always report the commit actually compiled. Attached to the
// HaishinKit target in Package.swift.
//
// Why a system shell and not a source-built tool:
//   - SwiftPM forbids a *prebuild* command from running executables built from
//     source; and
//   - a source-built tool gets compiled for the iOS destination too, where
//     `Process` (needed to invoke git) does not exist.
// So the git lookup + file write happen inside `/bin/sh` (or `cmd.exe` on
// Windows), which are system executables.
@main
struct HaishinKitRevisionPlugin: BuildToolPlugin {
    func createBuildCommands(context: PluginContext, target: Target) async throws -> [Command] {
        let outputDirectory = context.pluginWorkDirectoryURL
        let outputFile = outputDirectory.appendingPathComponent("HaishinKitRevision.swift")
        let packageDirectory = context.package.directoryURL.path
        let displayName = "Generate kHaishinKitRevision (\(target.name))"

        #if os(Windows)
        let script = """
        set "REV="
        for /f "usebackq tokens=*" %%r in (`git -C "\(packageDirectory)" rev-parse --short HEAD 2^>nul`) do set "REV=%%r"
        if not defined REV set "REV=unknown"
        > "\(outputFile.path)" echo // Generated by HaishinKitRevisionPlugin -- do not edit.
        >> "\(outputFile.path)" echo public let kHaishinKitRevision = "%REV%"
        """
        return [
            .prebuildCommand(
                displayName: displayName,
                executable: URL(fileURLWithPath: "C:\\Windows\\System32\\cmd.exe"),
                arguments: ["/c", script],
                outputFilesDirectory: outputDirectory
            )
        ]
        #else
        let script = """
        rev=$(git -C "\(packageDirectory)" rev-parse --short HEAD 2>/dev/null || echo unknown)
        printf '// Generated by HaishinKitRevisionPlugin -- do not edit.\\npublic let kHaishinKitRevision = "%s"\\n' "$rev" > "\(outputFile.path)"
        """
        return [
            .prebuildCommand(
                displayName: displayName,
                executable: URL(fileURLWithPath: "/bin/sh"),
                arguments: ["-c", script],
                outputFilesDirectory: outputDirectory
            )
        ]
        #endif
    }
}
