import Foundation

// RevisionTool — invoked by HaishinKitRevisionPlugin (Plugins/) to generate a
// Swift source exposing `kHaishinKitRevision` from the checkout's git HEAD.
//
// Usage: RevisionTool <packageDir> <outputFile>
//
// Always writes the output file (falling back to "unknown") so the build never
// fails when git is unavailable.

let arguments = CommandLine.arguments
let packageDirectory = arguments.count > 1 ? arguments[1] : FileManager.default.currentDirectoryPath
let outputFile = arguments.count > 2 ? arguments[2] : "HaishinKitRevision.swift"

func run(_ executable: String, _ arguments: [String]) -> String? {
    let process = Process()
    process.executableURL = URL(fileURLWithPath: executable)
    process.arguments = arguments
    let output = Pipe()
    process.standardOutput = output
    process.standardError = Pipe()
    do {
        try process.run()
    } catch {
        return nil
    }
    process.waitUntilExit()
    guard process.terminationStatus == 0 else {
        return nil
    }
    let data = output.fileHandleForReading.readDataToEndOfFile()
    let value = String(data: data, encoding: .utf8)?.trimmingCharacters(in: .whitespacesAndNewlines)
    return (value?.isEmpty == false) ? value : nil
}

func currentRevision() -> String {
    #if os(Windows)
    if let command = ProcessInfo.processInfo.environment["ComSpec"] ?? ProcessInfo.processInfo.environment["COMSPEC"],
       let value = run(command, ["/c", "git", "-C", packageDirectory, "rev-parse", "--short", "HEAD"]) {
        return value
    }
    #else
    if let value = run("/usr/bin/env", ["git", "-C", packageDirectory, "rev-parse", "--short", "HEAD"]) {
        return value
    }
    #endif
    return "unknown"
}

let contents = """
// Generated by HaishinKitRevisionPlugin — do not edit.
// Source: git rev-parse --short HEAD of the package checkout.
public let kHaishinKitRevision = "\(currentRevision())"
"""

do {
    try contents.write(toFile: outputFile, atomically: true, encoding: .utf8)
} catch {
    _ = FileManager.default.createFile(atPath: outputFile, contents: Data(contents.utf8))
    FileHandle.standardError.write(Data("RevisionTool: direct write fallback (\(error))\n".utf8))
}
